### ISSUE TITLE
build app and kext for latest MacOS 

### ISSUE THREAD

**Issue by d3fa** [i3roly/C-Media#1]
Hi
Can you make plz build for mac os Monterey? :)
(asus xonar dx, hackintosh)

**Comment by i3roly** [comment]
hi,

currently my mac pro is on 10.14 with no plans to upgrade, and my macbook pro is on 10.15 with no plans to upgrade either.

this kext was built with macos deployment target 10.7, but i'm guessing you've tried and it doesn't work.

if it doesn't, i don't have a solution at this time unfortunately. sorry.

**Comment by d3fa** [comment]
Hackintosh Ventura 13.3.1 OpenCore
fuck yeah it's all works!!
i did the wrong thing - i put Kext in /Volumes/EFI/EFI/OC/Kexts and its does't work for me. Here is right way 

1. Disable SIP (sign kext) in opencore: csr-active-config = 01000000 (disable Kext Signing)
3. clear NVRAM
4. sudo cp -r PCIAudioDriver.kext **/Library/Extensions/** 
5. sudo kextutil -v PCIAudioDriver.kext or sudo kextload -v PCIAudioDriver.kext (don't remember)
6. gives rights in settings, reboot if needed

And of course Hallab.app didn't work - ERROR without any chance =)
1. chmod +x HALLab.app/Contents/MacOS/HALLab
2. give rights in system settings
3. run HALLAB app

Sorry for bad english 
Thanks you man!
